### ISSUE TITLE
Rois for kinetix22

### ISSUE THREAD

**Issue by youssef4991** [Photometrics/PyVCAM#38]
Hi,
I have been testing out the various tests codes on the PyVCam github. The multi_rois test does not seem to work for my kinetix22 camera, the error message is the following:

[Running] python -u "c:\Program Files\Photometrics\PyVCAM-master\PyVCAM-master\tests\multi_rois.py"
ROI: 0 ( 750,  300) ( 949,  499)	Min:73	Max:112	Average:94	Frame Rate: 0.0	Frame Count: 1
Traceback (most recent call last):
  File "c:\Program Files\Photometrics\PyVCAM-master\PyVCAM-master\tests\multi_rois.py", line 61, in <module>
    main()
  File "c:\Program Files\Photometrics\PyVCAM-master\PyVCAM-master\tests\multi_rois.py", line 35, in main
    s1 = frame['meta_data']['roi_headers'][roi_index]['roi']['s1']
IndexError: list index out of range

the function set_roi does not seem to add any roi to the roi list, in fact when trying to access the rois property separately using a simple (print(cam.rois)), it seems like it does not exist,, error message:
Traceback (most recent call last):
  File "c:\Program Files\Photometrics\PyVCAM-master\PyVCAM-master\tests\meta_data.py", line 44, in <module>
    main()
  File "c:\Program Files\Photometrics\PyVCAM-master\PyVCAM-master\tests\meta_data.py", line 16, in main
    print(cam.rois)
AttributeError: 'Camera' object has no attribute 'rois'

Is this known behavior ? How can I solve this problem ?

Thank you

**Comment by vondrejPM** [comment]
Unfortunately, the use of Multi-ROI with Kinetix is limited by the camera firmware version. The current camera firmware (30.38.05) does not support Multi-ROI feature. This feature will be supported in the next firmware release but only on the 16-bit (Dynamic Range) mode.
